// DO NOT EDIT - generated by running:
// 	go run genversion.go
//
// Re-run this command when the Swiss Ephemeris is updated.
//

#define SWEX_VERSION 21002
#define SWEX_VERSION_MAJOR 2
#define SWEX_VERSION_MINOR 10
#define SWEX_VERSION_PATCH 2
