// DO NOT EDIT - generated by running:
// 	go run gensweversion.go
//
// Re-run this command when the Swiss Ephemeris is updated.
//

#define SWEX_VERSION 20600
#define SWEX_VERSION_MAJOR 2
#define SWEX_VERSION_MINOR 6
#define SWEX_VERSION_PATCH 0
